[project]
name = "riitag-rpc"
version = "0.1.0"
description = "A Discord rich presence for RiiTag - Forked to work with riitag.t0g3pii.de"
readme = "README.md"
authors = [
    { name = "zydezu", email = "50119098+zydezu@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "charset-normalizer<3.0",
    "nest-asyncio~=1.5.6",
    "prompt-toolkit~=3.0.39",
    "pyperclip~=1.9.0",
    "pypresence~=4.6.1",
    "requests~=2.31.0",
    "sentry-sdk~=1.28.1",
]
